#-------------------------------------------------------
# GENERAL
#-------------------------------------------------------
#[[plugins]]
#repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
'''


#-------------------------------------------------------
# ファイル操作関連
#-------------------------------------------------------
# vim 用の統合ユーザインターフェース
[[plugins]]
repo = 'Shougo/unite.vim'

# ファイラー
[[plugins]]
repo        = 'Shougo/vimfiler'
hook_source = '''
'''
# 非同期処理
[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'
hook_post_update = 'call delphinus#init#vimproc#hook_post_update()'
#-------------------------------------------------------
# Themas of Vim
#-------------------------------------------------------
# スキーマ着せ替えプラグイン
[[plugins]]
repo = 'ujihisa/unite-colorscheme'

# カラースキーマ群
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'croaker/mustang-vim'
[[plugins]]
repo = 'jeffreyiacono/vim-colors-wombat'
[[plugins]]
repo = 'nanotech/jellybeans.vim'
[[plugins]]
repo = 'vim-scripts/Lucius'
[[plugins]]
repo = 'vim-scripts/Zenburn'
[[plugins]]
repo = 'mrkn/mrkn256.vim'
[[plugins]]
repo = 'jpo/vim-railscasts-theme'
[[plugins]]
repo = 'therubymug/vim-pyte'
[[plugins]]
repo = 'tomasr/molokai'

