add_newline = true
format = """
$username $directory\n$character
"""

[username]
show_always = true
style_user = "green"
format = '[\[$user\]]($style)'

[hostname]
ssh_only = false
style = "green"
format = ""
trim_at = "."

[directory]
style = "bright-black"
format = "[$path]($style)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bright-black"
format = " [\\($branch\\)]($style)"

[git_status]
style = "cyan"
format = "[$all_status$ahead_behind]($style)"
staged = "!"
modified = "+"
untracked = "?"

[character]
success_symbol = "%"
error_symbol = "%"
vimcmd_symbol = "%"
